use kernex_policy::FilesystemPolicy;

use crate::error::{LandlockError, LinuxError, SeccompError};
use crate::spawn::{LandlockBuilt, SandboxReady, SandboxedSpawn, SeccompApplied};

// ---------------------------------------------------------------------------
// SandboxBackend trait
// ---------------------------------------------------------------------------

/// Abstraction over the Linux kernel enforcement APIs.
///
/// The trait exists to make the enforcement sequence testable without real
/// kernel calls. In production, [`LinuxSandboxBackend`] implements this trait
/// by calling into Landlock and seccomp. In tests, `MockSandboxBackend`
/// (generated by `mockall`) is used instead.
///
/// # Ordering
///
/// `setup_sandbox` calls the methods in this exact order:
///
/// 1. `build_landlock_ruleset` — creates and populates the Landlock ruleset fd
/// 2. `apply_seccomp`          — installs the seccomp BPF filter
/// 3. `LandlockBuilt::restrict_self` — calls `landlock_restrict_self()`
///
/// This ordering is required by the kernel security model (see kernel-security
/// skill). The type system enforces it: `SandboxedSpawn` can only be
/// constructed after both enforcement layers produce their marker types.
#[cfg_attr(test, mockall::automock)]
pub trait SandboxBackend {
    /// Build the Landlock filesystem ruleset from `policy`.
    ///
    /// Creates the ruleset fd and adds per-path rules. Does **not** call
    /// `restrict_self()` — that is deferred to [`LandlockBuilt::restrict_self`]
    /// so that the seccomp filter can be installed first.
    ///
    /// # Errors
    ///
    /// - [`LandlockError::NotSupported`] — kernel lacks Landlock support.
    /// - [`LandlockError::RulesetCreate`] — `landlock_create_ruleset()` failed.
    /// - [`LandlockError::RuleAdd`] — `landlock_add_rule()` failed for a path.
    fn build_landlock_ruleset(
        &self,
        policy: &FilesystemPolicy,
    ) -> Result<LandlockBuilt, LandlockError>;

    /// Install the seccomp BPF filter.
    ///
    /// Compiles and installs the mandatory syscall blocklist including the
    /// x86-64 architecture check as the first BPF instruction.
    ///
    /// # Errors
    ///
    /// - [`SeccompError::CompileError`] — BPF program failed to compile.
    /// - [`SeccompError::InstallError`] — `prctl(PR_SET_SECCOMP, ...)` failed.
    fn apply_seccomp(&self) -> Result<SeccompApplied, SeccompError>;
}

// ---------------------------------------------------------------------------
// setup_sandbox — orchestrator enforcing the kernel-mandated ordering
// ---------------------------------------------------------------------------

/// Set up the full sandbox for a child process.
///
/// Calls `backend` methods in the kernel-required order:
/// 1. Build Landlock ruleset
/// 2. Install seccomp BPF filter
/// 3. Lock Landlock via `restrict_self()`
///
/// Returns [`SandboxReady::Full`] when both enforcement layers are active, or
/// [`SandboxReady::SeccompOnly`] when Landlock was skipped due to the 16-layer
/// depth limit (only when `strict = false`).
///
/// # Errors
///
/// - Any [`LandlockError`] except `DepthLimitExceeded` when `strict = false`.
/// - Any [`SeccompError`].
///
/// # Panics
///
/// Never panics.
pub fn setup_sandbox<B: SandboxBackend>(
    backend: &B,
    policy: &FilesystemPolicy,
    strict: bool,
) -> Result<SandboxReady, LinuxError> {
    // Step 1: Build the Landlock ruleset (does NOT call restrict_self yet).
    let landlock_build_result = backend.build_landlock_ruleset(policy);

    // Step 2: Install seccomp BPF filter — always done, even if Landlock failed.
    // This ensures the mandatory syscall blocklist is always active.
    let seccomp = backend.apply_seccomp()?;

    // Step 3: Handle Landlock result and call restrict_self.
    match landlock_build_result {
        Ok(built) => {
            // Step 3a: Lock the ruleset — landlock_restrict_self().
            match built.restrict_self() {
                Ok(landlock) => Ok(SandboxReady::Full(SandboxedSpawn::new(landlock, seccomp))),
                Err(LandlockError::DepthLimitExceeded) if !strict => {
                    tracing::warn!(
                        "Landlock depth limit exceeded (16 rulesets already stacked); \
                         falling back to seccomp-only enforcement"
                    );
                    Ok(SandboxReady::SeccompOnly(seccomp))
                }
                Err(e) => Err(LinuxError::Landlock(e)),
            }
        }
        Err(LandlockError::DepthLimitExceeded) if !strict => {
            tracing::warn!(
                "Landlock depth limit exceeded on ruleset build; \
                 falling back to seccomp-only enforcement"
            );
            Ok(SandboxReady::SeccompOnly(seccomp))
        }
        Err(LandlockError::NotSupported) if !strict => {
            tracing::warn!(
                "Landlock LSM is not supported on this kernel; \
                 falling back to seccomp-only enforcement"
            );
            Ok(SandboxReady::SeccompOnly(seccomp))
        }
        Err(e) => Err(LinuxError::Landlock(e)),
    }
}

// ---------------------------------------------------------------------------
// LinuxSandboxBackend — real implementation (Linux only)
// ---------------------------------------------------------------------------

/// The production implementation of [`SandboxBackend`].
///
/// Makes real `landlock_*` and `prctl(PR_SET_SECCOMP, ...)` syscalls.
/// Only available on Linux.
#[cfg(target_os = "linux")]
pub struct LinuxSandboxBackend;

#[cfg(target_os = "linux")]
impl SandboxBackend for LinuxSandboxBackend {
    fn build_landlock_ruleset(
        &self,
        policy: &FilesystemPolicy,
    ) -> Result<LandlockBuilt, LandlockError> {
        crate::landlock::build_ruleset(policy)
    }

    fn apply_seccomp(&self) -> Result<SeccompApplied, SeccompError> {
        crate::seccomp::build_and_install()
    }
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;
    use mockall::Sequence;

    fn default_policy() -> FilesystemPolicy {
        FilesystemPolicy::default()
    }

    // -- Enforcement ordering ------------------------------------------------

    #[test]
    fn test_setup_sandbox_calls_landlock_before_seccomp() {
        // Verifies the kernel-required ordering via mockall Sequence.
        let mut seq = Sequence::new();
        let mut mock = MockSandboxBackend::new();

        mock.expect_build_landlock_ruleset()
            .times(1)
            .in_sequence(&mut seq)
            .returning(|_| Ok(LandlockBuilt::dummy()));

        mock.expect_apply_seccomp()
            .times(1)
            .in_sequence(&mut seq)
            .returning(|| Ok(SeccompApplied::new()));

        let result = setup_sandbox(&mock, &default_policy(), false);
        assert!(result.is_ok());
    }

    #[test]
    fn test_setup_sandbox_returns_full_when_both_succeed() {
        let mut mock = MockSandboxBackend::new();

        mock.expect_build_landlock_ruleset()
            .returning(|_| Ok(LandlockBuilt::dummy()));

        mock.expect_apply_seccomp()
            .returning(|| Ok(SeccompApplied::new()));

        let result = setup_sandbox(&mock, &default_policy(), false).unwrap();
        assert!(result.is_full());
    }

    // -- Landlock depth limit (graceful degradation) -------------------------

    #[test]
    fn test_setup_sandbox_degrades_on_depth_exceeded_non_strict() {
        let mut mock = MockSandboxBackend::new();

        mock.expect_build_landlock_ruleset()
            .returning(|_| Err(LandlockError::DepthLimitExceeded));

        // seccomp must still be installed even when Landlock fails.
        mock.expect_apply_seccomp()
            .times(1)
            .returning(|| Ok(SeccompApplied::new()));

        let result = setup_sandbox(&mock, &default_policy(), false).unwrap();
        assert!(result.is_degraded());
    }

    #[test]
    fn test_setup_sandbox_strict_mode_aborts_on_depth_exceeded() {
        let mut mock = MockSandboxBackend::new();

        mock.expect_build_landlock_ruleset()
            .returning(|_| Err(LandlockError::DepthLimitExceeded));

        // seccomp is still applied before we propagate the error.
        mock.expect_apply_seccomp()
            .returning(|| Ok(SeccompApplied::new()));

        let result = setup_sandbox(&mock, &default_policy(), true);
        assert!(matches!(
            result,
            Err(LinuxError::Landlock(LandlockError::DepthLimitExceeded))
        ));
    }

    #[test]
    fn test_setup_sandbox_degrades_on_not_supported_non_strict() {
        // LandlockError::NotSupported with strict=false → seccomp-only (graceful degradation).
        let mut mock = MockSandboxBackend::new();

        mock.expect_build_landlock_ruleset()
            .returning(|_| Err(LandlockError::NotSupported));

        mock.expect_apply_seccomp()
            .times(1)
            .returning(|| Ok(SeccompApplied::new()));

        let result = setup_sandbox(&mock, &default_policy(), false);
        assert!(
            result.is_ok(),
            "NotSupported should degrade gracefully in non-strict mode"
        );
        assert!(result.unwrap().is_degraded());
    }

    #[test]
    fn test_setup_sandbox_strict_aborts_on_not_supported() {
        // LandlockError::NotSupported with strict=true → propagates error.
        let mut mock = MockSandboxBackend::new();

        mock.expect_build_landlock_ruleset()
            .returning(|_| Err(LandlockError::NotSupported));

        mock.expect_apply_seccomp()
            .returning(|| Ok(SeccompApplied::new()));

        let result = setup_sandbox(&mock, &default_policy(), true);
        assert!(matches!(
            result,
            Err(LinuxError::Landlock(LandlockError::NotSupported))
        ));
    }

    #[test]
    fn test_setup_sandbox_propagates_other_landlock_error() {
        // Other Landlock errors (e.g. RulesetCreate) always propagate, even non-strict.
        let mut mock = MockSandboxBackend::new();

        mock.expect_build_landlock_ruleset()
            .returning(|_| Err(LandlockError::RulesetCreate("EINVAL".to_string())));

        mock.expect_apply_seccomp()
            .returning(|| Ok(SeccompApplied::new()));

        let result = setup_sandbox(&mock, &default_policy(), false);
        assert!(
            matches!(
                result,
                Err(LinuxError::Landlock(LandlockError::RulesetCreate(_)))
            ),
            "non-NotSupported Landlock errors should always propagate"
        );
    }

    #[test]
    fn test_setup_sandbox_propagates_seccomp_error() {
        let mut mock = MockSandboxBackend::new();

        mock.expect_build_landlock_ruleset()
            .returning(|_| Ok(LandlockBuilt::dummy()));

        mock.expect_apply_seccomp()
            .returning(|| Err(SeccompError::InstallError("prctl failed".into())));

        let result = setup_sandbox(&mock, &default_policy(), false);
        assert!(matches!(result, Err(LinuxError::Seccomp(_))));
    }

    #[test]
    fn test_setup_sandbox_seccomp_still_applied_when_landlock_depth_exceeded() {
        // Even in the depth-exceeded case, seccomp must be applied (seccomp is
        // always active regardless of Landlock availability).
        let mut mock = MockSandboxBackend::new();

        mock.expect_build_landlock_ruleset()
            .returning(|_| Err(LandlockError::DepthLimitExceeded));

        mock.expect_apply_seccomp()
            .times(1) // Must be called exactly once
            .returning(|| Ok(SeccompApplied::new()));

        let _ = setup_sandbox(&mock, &default_policy(), false);
    }

    // -- Policy content forwarded to backend --------------------------------

    #[test]
    fn test_setup_sandbox_passes_policy_to_landlock() {
        let mut mock = MockSandboxBackend::new();
        let policy = FilesystemPolicy {
            allow_read: vec!["/tmp".into()],
            ..FilesystemPolicy::default()
        };

        mock.expect_build_landlock_ruleset()
            .withf(|p| p.allow_read == vec![std::path::PathBuf::from("/tmp")])
            .times(1)
            .returning(|_| Ok(LandlockBuilt::dummy()));

        mock.expect_apply_seccomp()
            .returning(|| Ok(SeccompApplied::new()));

        let _ = setup_sandbox(&mock, &policy, false);
    }
}
