use kernex_policy::KernexPolicy;

use crate::error::CoreError;

/// Abstraction over OS sandbox enforcement (Landlock + seccomp on Linux,
/// Endpoint Security on macOS).
///
/// `kernex-core` itself is platform-agnostic — no `#[cfg(target_os)]`
/// anywhere. All OS-specific code lives in `kernex-linux` or `kernex-macos`.
/// Those crates implement this trait and pass a `Box<dyn SandboxBackend>` into
/// the core engine at startup.
///
/// # Ordering invariant
///
/// Implementors must apply all enforcement layers **before** returning `Ok(())`.
/// The caller (`run_session`) invokes `setup()` before `execve()`.
///
/// # Test support
///
/// In unit tests, `MockSandboxBackend` (generated by `mockall::automock`) is
/// used so that no real kernel calls are made.
#[cfg_attr(test, mockall::automock)]
pub trait SandboxBackend: Send + Sync {
    /// Apply OS enforcement layers from `policy` to the current process.
    ///
    /// On Linux this builds the Landlock ruleset, installs the seccomp BPF
    /// filter, and calls `restrict_self()` in the kernel-required order. On
    /// macOS it registers the Endpoint Security client and subscribes to AUTH
    /// events for the target PID.
    ///
    /// # Errors
    ///
    /// Returns [`CoreError::Sandbox`] if any enforcement layer fails and
    /// the failure cannot be gracefully degraded (e.g. `strict = true`).
    fn setup(&self, policy: &KernexPolicy, strict: bool) -> Result<(), CoreError>;
}
